config/routes.rb
Rails.application.routes.draw do
  get 'email/create'
  resources :posts
  root 'posts#index'
  get 'sessions/new'
  get '/email' => 'email#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/email' => 'email#create'
  get '/user' => 'users#show'
  delete '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
	def self.to_csv
    attributes = %w{email}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploaders :photos, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def create
  	email = params[:post][:email]
  	Email.find_or_create_by(email: email) if email
  end

  def index
  	@emails = Email.all
  	respond_to do |format|
    	format.html
    	format.csv { send_data(@emails.to_csv) }
    end
  end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper 

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @photos = @post.photos
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:address, :city, :state, :zip, :square_feet, :bathroom, :bedroom, :description, :price, :youtube, {photos: []})
    end

    def require_login
      unless logged_in?
        redirect_to login_path
      end
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def new
  end

  def create
  	user = User.find_by(name: params[:session][:name].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      puts "Logged in!!"
  		redirect_to user
  	else
      puts 'Failed login'
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper 

	before_action :require_login

	def show
		@user = User.find(1)
		@posts = Post.all

		@emails = Post.all
  end

	private 

	def require_login
      unless logged_in?
        redirect_to login_path
      end
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
	  session[:user_id] = user.id
	end 

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user 
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in(user)
				@current_user = user
			end
		end
	end 

	def logged_in?
		!current_user.nil?
	end 

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cardinal Rules Property Investments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="card card-container post-form" id="text">
	<% if @photos %>
	<h3>Edit listing</h3>
		<div class="photos">
			<% @photos.each do |img| %>
				<%= image_tag (img.to_s) %>
			<% end %>
		</div>
	<% end %>
	<%= form_for(:post, url: posts_path) do |f| %>
		  	<%= f.label :address %>
				<%= f.text_field :address, class: "address form-control", placeholder: "Enter Address Here", required: true %>
				<%= f.label :city %>
				<%= f.text_field :city, class: "city form-control"%>
				<%= f.label :state %>
				<%= f.text_field :state, class: "state form-control" %>
				<%= f.label :zip %>
				<%= f.text_field :zip, class: 'zip form-control', required: true %>
				<%= f.label :bedroom, id:"bedrooms" %>
				<%= f.select(:bedroom, options_for_select([['1', 1],['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7]]), id: 'bedroooms')%>
				<%= f.label :bathroom, id:'baths' %>
				<%= f.select(:bathroom, options_for_select([['1', 1], ['1.5', 1.5], ['2', 2], ['2.5', 2.5], ['3', 3], ['3.5', 3.5], ['4', 4], ['4.5', 4.5], ['5', 5], ['5.5', 5.5], ['6', 6], ['6.5', 6]]), id:'baths')%>
				<br/><br/>
				<%= f.label :square_feet %>
				<%= f.text_field :square_feet, class: "square_feet form-control" %>
				<%= f.label :price %>
				<%= f.text_field :price, class: "price form-control" %>
				<%= f.label :description %>
				<%= f.text_area :description, class: "description form-control" %>
				<%= f.label :youtube_code %>
				<%= f.text_area :youtube, class: "form-control" %>
				<%= f.label :photo_upload %>
				<%= f.file_field :photos, multiple: true %>
				<%= f.submit "Submit", class: "form-control"%>
	<% end %>
</div>

app/views/posts/_new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="container">
  <div class="well well-sm quick-contact" id="top">
      <div class="row">
                  
                      <header class="responsive">
      <h1 id="logo">Cardinal Rules Property Investments</h1>
      <h3><strong>Call us:</strong> 502-909-5853</h3>
               <h3><%= mail_to "cardinalinvestmentproperty@gmail.com" do %>
  <strong>Email us:</strong> <span>cardinalinvestmentproperty@gmail.com</span>
<% end %></h3>
    </header>
          </div>
      </div>
  </div>
</div>

<div class="container-fluid">
  <div class="container container-pad" id="property-listings">  
      <div class="row"><% @posts.each do |post| %>
          <div class="col-sm-6"> 
              
              
              <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                  <div class="media">
                    <% if post.youtube %>
                      <div class="video" id='video<%=post.id%>'>
                        <iframe src='https://www.youtube.com/embed/<%=post.youtube %>' frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        <div id="close" onclick="document.getElementById('video<%=post.id%>').style.display = 'none';">Close</div>
                      </div>
                    <% end %>
                    <%= image_tag(post.photos.first.to_s, class: "responsive") %> 
                      <a class="pull-left" href="#" target="_parent">
                      

                      <div class="clearfix visible-sm"></div>

                      <div class="media-body fnt-smaller">
                          <a href="#" target="_parent"></a>

                          <h4 class="media-heading">
                            <%= number_to_currency(post.price, precision: 0) %><small class="pull-right"><%= post.address %></small></h4>


                          <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
                              <li>4,820 SqFt</li>

                              <li style="list-style: none">|</li>

                              <li><%= post.bedroom %> Beds</li>

                              <li style="list-style: none">|</li>

                              <li><%= post.bathroom %> Baths</li>
                              <br/>
                              <% if post.youtube %><li class="link" id="videos-click" onclick="document.getElementById('video<%=post.id%>').style.display = 'block';">Video</li><li>|</li><% end %>
                              <li class="link" id="photos-click">More Photos</li>
                          </ul>

                         
                      </div>
                  </div>
              </div><!-- End Listing-->
              
          </div><!-- End Col -->
          <% end %>
      </div><!-- End row -->
    </div><!-- End container -->
</div>

<%= render 'email/email' %>

app/views/posts/show.html.erb
<div class="card card-container" id="post-list">
	<p>
	  <strong>Address:</strong>
	  <%= @post.address %>
	</p>

	<p>
	  <strong>City:</strong>
	  <%= @post.city %>
	</p>

	<p>
	  <strong>State:</strong>
	  <%= @post.state %>
	</p>

	<p>
	  <strong>Zip:</strong>
	  <%= @post.zip %>
	</p>

	<% @post.photos.each do |path| %>
		<%= image_tag path.to_s, width: '350' %>
	<% end %>

	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Delete', post_path(@post), method: :delete %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/users/show.html.erb
<div class="control-wrapper">
	<div class="form-card">
		<%= render 'posts/form' %>
		</div>
		<div class="list-card">
		<div class="card card-container" id="list edit">
			<h2>Email List</h2>
			<ul><li><%= link_to 'CSV Download', email_path(:format => :csv )%></li></ul>
			<h2>Posted Listings</h2>
			<ul>
				<% @posts.each do |post| %>
				  <li class="listing"><%= link_to post.address, post %></li>
				<% end %>
			</ul>
		</div>
	</div
</div>